/**:
  ros__parameters:

    ### AUDIO PARAMS - these should not change across experiments
    n_channels: 16
    sample_rate: 44100
    downsample_rate: 32000
    frame_size: 44100
    scene_size: 44100
    scene_index: [0]
    labels: ['airport', 'bus', 'metro', 'metro_station', 'park', 'public_square', 'shopping_mall', 'street_pedestrian', 'street_traffic', 'tram']

    # Model path params
    project_name: DCASE23_Task1
    wandb_id: 'c0a7nzin'

    # Mel pre-processing parameters
    resample_rate: 32000
    window_size: 3072
    hop_size: 500
    n_fft: 4096
    n_mels: 256
    freqm: 48
    timem: 0
    fmin: 0
    fmax: 0
    fmin_aug_range: 1
    fmax_aug_range: 1000

    # Model parameters
    n_classes: 10
    in_channels: 1
    base_channels: 32
    channels_multiplier: 2.3
    expansion_rate: 3

/record_scene_results_node:
  ros__parameters:
    config_name: 'rn50_basic'

/clip_scene_rec:
  ros__parameters:
    update_interval: 1.0
    scene_labels: ['campus','courtyard','lab', 'lobby']
    scene_descriptions: ['a college campus','an outdoor courtyard','a lab', 'a lobby']
    clip_model: 'RN50'

### AUDIO BAYES ESTIMATOR PARAMS
/bayes_audio_scene_est:
  ros__parameters:

    scene_labels: ['campus','courtyard','lab','lobby']
    scene_prior: [.25,.25,.25,.25]

    sensor_names: ['dcase23']

    dcase23:
      obs_labels: ['airport', 'bus', 'metro', 'metro_station','park','public_square','shopping_mall','street_pedestrian','street_traffic','tram']
      sensor_model_coeffs: [9.0,15.0,44.0,23.0,197.0,8.0,1.0,1.0,49.0,1941.0,
                            4.0,294.0,6.0,12.0,724.0,3.0,1.0,3.0,19.0,1409.0,
                            19.0,142.0,2110.0,31.0,90.0,4.0,1.0,1.0,71.0,37.0,
                            469.0,49.0,201.0,464.0,977.0,1.0,73.0,16.0,22.0,180.0]
      topic: 'audio_scene_category'

### CLIP BAYES ESTIMATOR PARAMS
/bayes_clip_scene_est:
  ros__parameters:

    scene_labels: ['campus','courtyard','lab','lobby']
    scene_prior: [.25,.25,.25,.25]

    sensor_names: ['clip']

    clip:
      obs_labels: ['campus','courtyard','lab','lobby']
      sensor_model_coeffs: [38580.0,1.0,74.0,1.0,
                            42907.0,2.0,1.0,1.0,
                            5319.0,1.0,36867.0,5.0,
                            5402.0,1.0,2.0,36038.0]
      topic: 'clip_scene_category'

### FUSED BAYES ESTIMATOR PARAMS
/bayes_joint_scene_est:
  ros__parameters:

    loop_time_sec: 1.
    min_prob: .001
    max_prob: .999

    scene_labels: ['campus','courtyard','lab','lobby']
    scene_prior: [.25,.25,.25,.25]

    sensor_names: ['clip','dcase23']

    clip:
      obs_labels: ['campus','courtyard','lab','lobby']
      sensor_model_coeffs: [38580.0,1.0,74.0,1.0,
                            42907.0,2.0,1.0,1.0,
                            5319.0,1.0,36867.0,5.0,
                            5402.0,1.0,2.0,36038.0]
      topic: 'clip_scene_category'

    dcase23:
      obs_labels: ['airport', 'bus', 'metro', 'metro_station','park','public_square','shopping_mall','street_pedestrian','street_traffic','tram']
      sensor_model_coeffs: [9.0,15.0,44.0,23.0,197.0,8.0,1.0,1.0,49.0,1941.0,
                            4.0,294.0,6.0,12.0,724.0,3.0,1.0,3.0,19.0,1409.0,
                            19.0,142.0,2110.0,31.0,90.0,4.0,1.0,1.0,71.0,37.0,
                            469.0,49.0,201.0,464.0,977.0,1.0,73.0,16.0,22.0,180.0]
      topic: 'audio_scene_category'

### EXPERIMENT MANAGER NODE
scene_exp_mgr:
  ros__parameters:
    exp_configs: ['config/exp1_scene_cfgs/rn50_basic.yaml',
                  'config/exp1_scene_cfgs/rn50_detailed.yaml',
                  'config/exp1_scene_cfgs/vitb32_basic.yaml',
                  'config/exp1_scene_cfgs/vitb32_detailed.yaml',
                  'config/exp1_scene_cfgs/vitl14_basic.yaml',
                  'config/exp1_scene_cfgs/vitl14_detailed.yaml']
    mcap_dir: 'c2hi_ws/src/c2hi/bags/exp_data'