/record_scene_results_node:
  ros__parameters:
    config_name: 'vitb32_detailed'
 
### CLIP SCENE ESTIMATION PARAMS
/clip_scene_rec:
  ros__parameters:
    scene_descriptions: ['a picture of a public outdoor area with high social activity',
                         'a picture of a private outdoor area with low social activity',
                         'a picture of a private indoor area with low social activity',
                         'a picture of a public indoor area with high social activity']
    clip_model: 'ViT-B/32'

### CLIP BAYES ESTIMATOR PARAMS
/bayes_clip_scene_est:
  ros__parameters:

    clip:
      sensor_model_coeffs: [656.0,37998.0,1.0,1.0,
                            1.0,42908.0,1.0,1.0,
                            1.0,1.0,42189.0,1.0,
                            1.0,2.0,35162.0,6278.0]

### FUSED BAYES ESTIMATOR PARAMS
/bayes_joint_scene_est:
  ros__parameters:

    clip:
      sensor_model_coeffs: [656.0,37998.0,1.0,1.0,
                            1.0,42908.0,1.0,1.0,
                            1.0,1.0,42189.0,1.0,
                            1.0,2.0,35162.0,6278.0]
