/record_scene_results_node:
  ros__parameters:
    config_name: 'vitl14_detailed'

### CLIP SCENE ESTIMATION PARAMS
/clip_scene_rec:
  ros__parameters:
    scene_descriptions: ['a picture of a public outdoor area with high social activity',
                         'a picture of a private outdoor area with low social activity',
                         'a picture of a private indoor area with low social activity',
                         'a picture of a public indoor area with high social activity']
    clip_model: 'ViT-L/14'

### CLIP BAYES ESTIMATOR PARAMS
/bayes_clip_scene_est:
  ros__parameters:
    clip:
      sensor_model_coeffs: [35194.0,3460.0,1.0,1.0,
                            156.0,42753.0,1.0,1.0,
                            1.0,51.0,41927.0,213.0,
                            1.0,17.0,4785.0,36640.0]

### FUSED BAYES ESTIMATOR PARAMS
/bayes_joint_scene_est:
  ros__parameters:
    clip:
      sensor_model_coeffs: [35194.0,3460.0,1.0,1.0,
                            156.0,42753.0,1.0,1.0,
                            1.0,51.0,41927.0,213.0,
                            1.0,17.0,4785.0,36640.0]
