### MULTIMODAL PROCESSING - SEMANTIC FUSION NODE
/semantic_fusion_node:
  ros__parameters:

    role_rec_methods: ['artag']
    command_rec_methods: ['verbal']

/pra_node:
  ros__parameters:
    # Sound source localization
    ssl_algo: 'MUSIC'

/speech_rec_node:
  ros__parameters:

    trigger_level: 3.0
    am_bundle: 'WAV2VEC2_ASR_LARGE_960H'
    lm_weight: 3.
    word_score: 3.
    sil_score: 1.